apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: portfolio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Plataforma de observabilidade multi-linguagem no AWS EKS"

  sourceRepos:
    - "https://github.com/SEU_USUARIO/gitops-argocd"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"
    - "https://open-telemetry.github.io/opentelemetry-helm-charts"
    - "https://argoproj.github.io/argo-helm"

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: apps
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  roles:
    - name: admin
      description: Acesso completo ao projeto portfolio
      policies:
        - p, proj:portfolio:admin, applications, *, portfolio/*, allow
      groups:
        - portfolio-admins
