apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Primeira coisa a ser criada
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: portfolio

  source:
    repoURL: https://github.com/SEU_USUARIO/gitops-argocd
    targetRevision: HEAD
    path: kubernetes/namespaces

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false      # Nunca deletar namespaces automaticamente
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
