apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # Após Prometheus estar pronto
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: portfolio

  sources:
    - chart: tempo
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: ">=1.10.0"
      helm:
        valueFiles:
          - $values/kubernetes/monitoring/tempo/values.yaml

    - repoURL: https://github.com/SEU_USUARIO/gitops-argocd
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
