spring.application.name=java-app
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

# Metrics
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

# Tracing
management.tracing.sampling.probability=1.0
