apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/go-app/deployment.yaml
  - ../../../apps/go-app/service.yaml
  - ../../../apps/go-app/servicemonitor.yaml

images:
  - name: go-app
    newName: SEU_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/go-app
    newTag: latest
